# Generated by Django 5.2.12 on 2026-03-06 11:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_name",
                    models.CharField(
                        help_text="User's first name.",
                        max_length=100,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="User's last name.",
                        max_length=100,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Used as the login identifier.",
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Student"), ("teacher", "Teacher")],
                        help_text="Determines whether the user is a Student or Teacher.",
                        max_length=10,
                        verbose_name="Role",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Profile picture.",
                        null=True,
                        upload_to="avatars/%Y/%m/",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Algerian phone number (e.g. 0555 123 456).",
                        max_length=20,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Used for age verification and personalization.",
                        null=True,
                        verbose_name="Date of Birth",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        help_text="Optional gender field.",
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "wilaya",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "Adrar"),
                            ("02", "Chlef"),
                            ("03", "Laghouat"),
                            ("04", "Oum El Bouaghi"),
                            ("05", "Batna"),
                            ("06", "Béjaïa"),
                            ("07", "Biskra"),
                            ("08", "Béchar"),
                            ("09", "Blida"),
                            ("10", "Bouira"),
                            ("11", "Tamanrasset"),
                            ("12", "Tébessa"),
                            ("13", "Tlemcen"),
                            ("14", "Tiaret"),
                            ("15", "Tizi Ouzou"),
                            ("16", "Alger"),
                            ("17", "Djelfa"),
                            ("18", "Jijel"),
                            ("19", "Sétif"),
                            ("20", "Saïda"),
                            ("21", "Skikda"),
                            ("22", "Sidi Bel Abbès"),
                            ("23", "Annaba"),
                            ("24", "Guelma"),
                            ("25", "Constantine"),
                            ("26", "Médéa"),
                            ("27", "Mostaganem"),
                            ("28", "M'Sila"),
                            ("29", "Mascara"),
                            ("30", "Ouargla"),
                            ("31", "Oran"),
                            ("32", "El Bayadh"),
                            ("33", "Illizi"),
                            ("34", "Bordj Bou Arréridj"),
                            ("35", "Boumerdès"),
                            ("36", "El Tarf"),
                            ("37", "Tindouf"),
                            ("38", "Tissemsilt"),
                            ("39", "El Oued"),
                            ("40", "Khenchela"),
                            ("41", "Souk Ahras"),
                            ("42", "Tipaza"),
                            ("43", "Mila"),
                            ("44", "Aïn Defla"),
                            ("45", "Naâma"),
                            ("46", "Aïn Témouchent"),
                            ("47", "Ghardaïa"),
                            ("48", "Relizane"),
                            ("49", "Timimoun"),
                            ("50", "Bordj Badji Mokhtar"),
                            ("51", "Ouled Djellal"),
                            ("52", "Béni Abbès"),
                            ("53", "In Salah"),
                            ("54", "In Guezzam"),
                            ("55", "Touggourt"),
                            ("56", "Djanet"),
                            ("57", "El M'Ghair"),
                            ("58", "El Ménéa"),
                        ],
                        help_text="Algerian province of residence.",
                        max_length=2,
                        verbose_name="Wilaya",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user has verified their email address.",
                        verbose_name="Is Verified",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Optional short student bio.",
                        verbose_name="Bio",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current grade the student is enrolled in.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="curriculum.grade",
                        verbose_name="Grade",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        help_text="Filière for Secondaire students (e.g. Sciences Expérimentales). Leave blank for Primaire and Moyen students.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="curriculum.specialty",
                        verbose_name="Specialty",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user account associated with this student profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Optional teacher bio or professional description.",
                        verbose_name="Bio",
                    ),
                ),
                (
                    "is_verified_teacher",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this teacher has been verified by an admin. Only verified teachers can publish resources.",
                        verbose_name="Is Verified Teacher",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        help_text="The education level this teacher teaches (e.g. Moyen).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teachers",
                        to="curriculum.level",
                        verbose_name="Level",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="The subject this teacher specializes in. Must belong to the selected level.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teachers",
                        to="curriculum.subject",
                        verbose_name="Subject",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user account associated with this teacher profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Profile",
                "verbose_name_plural": "Teacher Profiles",
            },
        ),
    ]
