# Generated by Django 5.2.12 on 2026-03-24 09:37

from django.db import migrations

OFFERS = [
    {
        "tier": "free",
        "name": "Free",
        "description": "Get started with the basics.",
        "features": [
            "Access to all free resources",
            "Browse courses and exercises",
            "Progress tracking",
            "-Priority support",
            "-Downloadable resources",
            "-Live tutoring",
        ],
        "is_active": True,
        "order": 1,
    },
    {
        "tier": "standard",
        "name": "Standard",
        "description": "Everything you need to succeed.",
        "features": [
            "Everything in Free",
            "Access to all premium courses",
            "All exercises and solutions",
            "Downloadable resources",
            "Email support",
            "-Live tutoring sessions",
        ],
        "is_active": True,
        "order": 2,
    },
    {
        "tier": "premium",
        "name": "Premium",
        "description": "The complete learning experience.",
        "features": [
            "Everything in Standard",
            "Live tutoring sessions",
            "Priority support",
            "Early access to new content",
            "Personalised study plan",
            "Offline downloads",
        ],
        "is_active": True,
        "order": 3,
    },
]


# (offer_tier + interval) maps to unique_together on the Plan model
PLANS = [
    # ── Standard ──────────────────────────────────────────────────────────────
    {
        "offer_tier": "standard",
        "interval": "month",
        "stripe_price_id": "price_1T8nGZAjndLhV4TCabCZnGEo",
        "price": "9.99",
        "original_price": None,
        "is_active": True,
        "is_popular": False,
    },
    {
        "offer_tier": "standard",
        "interval": "6month",
        "stripe_price_id": "price_1T8nHLAjndLhV4TCg1BAt44g",
        "price": "49.99",
        "original_price": "59.94",
        "is_active": True,
        "is_popular": True,
    },
    {
        "offer_tier": "standard",
        "interval": "year",
        "stripe_price_id": "price_1T8nHiAjndLhV4TC9scvvhGi",
        "price": "89.99",
        "original_price": "119.88",
        "is_active": True,
        "is_popular": False,
    },
    # ── Premium ───────────────────────────────────────────────────────────────
    {
        "offer_tier": "premium",
        "interval": "month",
        "stripe_price_id": "price_1T8nIwAjndLhV4TCip6oAdk5",
        "price": "19.99",
        "original_price": None,
        "is_active": True,
        "is_popular": False,
    },
    {
        "offer_tier": "premium",
        "interval": "6month",
        "stripe_price_id": "price_1T8nJzAjndLhV4TCPiMWdnBq",
        "price": "99.99",
        "original_price": "119.94",
        "is_active": True,
        "is_popular": True,
    },
    {
        "offer_tier": "premium",
        "interval": "year",
        "stripe_price_id": "price_1T8nKHAjndLhV4TCgCiY8SBI",
        "price": "179.99",
        "original_price": "239.88",
        "is_active": True,
        "is_popular": False,
    },
]


def seed_offers_and_plans(apps, schema_editor):
    Offer = apps.get_model("billing", "Offer")
    Plan = apps.get_model("billing", "Plan")

    for data in OFFERS:
        Offer.objects.get_or_create(
            tier=data["tier"],  # tier is unique — safe natural key
            defaults={k: v for k, v in data.items() if k != "tier"},
        )

    for data in PLANS:
        offer = Offer.objects.get(tier=data["offer_tier"])
        Plan.objects.get_or_create(
            offer=offer,
            interval=data["interval"],  # (offer, interval) is unique_together
            defaults={
                "stripe_price_id": data["stripe_price_id"],
                "price": data["price"],
                "original_price": data["original_price"],
                "is_active": data["is_active"],
                "is_popular": data["is_popular"],
            },
        )


def unseed_offers_and_plans(apps, schema_editor):
    Offer = apps.get_model("billing", "Offer")
    Plan = apps.get_model("billing", "Plan")

    Plan.objects.filter(
        offer__tier__in=[p["offer_tier"] for p in PLANS],
        interval__in=[p["interval"] for p in PLANS],
    ).delete()
    Offer.objects.filter(tier__in=[o["tier"] for o in OFFERS]).delete()


class Migration(migrations.Migration):

    # ↓ replace with your actual last migration filename (without .py)
    dependencies = [
        ("billing", "0002_alter_plan_stripe_price_id"),
    ]

    operations = [
        migrations.RunPython(
            seed_offers_and_plans,
            reverse_code=unseed_offers_and_plans,
        ),
    ]
