# Generated by Django 5.2.12 on 2026-03-06 18:30

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("content", "0003_resource_created_by_videoresource_created_by"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("curriculum", "0002_specialty_created_at_specialty_updated_at_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("question_text", models.TextField()),
                ("points", models.PositiveIntegerField(default=1)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("essay", "Essay"),
                            ("mcq", "Multiple Choice"),
                            ("tf", "True / False"),
                        ],
                        db_index=True,
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("advanced", "Advanced"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allow_multiple",
                    models.BooleanField(
                        default=False,
                        help_text="Whether students can select more than one correct answer.",
                        verbose_name="Allow Multiple",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Shown to the student after answering.",
                        verbose_name="Explanation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and discovering questions (e.g., 'python', 'beginner', 'tutorial', 'exam-prep')",
                        through="common.UUIDTaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multiple Choice Question",
                "verbose_name_plural": "Multiple Choice Questions",
                "db_table": "mcq_questions",
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="assessment.multiplechoicequestion",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instructions shown to students before taking the quiz",
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time limit in minutes (null = no time limit)",
                        null=True,
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of attempts allowed per user",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "passing_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=70.0,
                        help_text="Minimum percentage score to pass",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the quiz is visible to students",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the quiz becomes available (null = available immediately)",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the quiz closes (null = no end date)",
                        null=True,
                    ),
                ),
                (
                    "randomize_questions",
                    models.BooleanField(
                        default=False,
                        help_text="Randomize question order for each attempt",
                    ),
                ),
                (
                    "show_results_immediately",
                    models.BooleanField(
                        default=True,
                        help_text="Show results to student immediately after submission",
                    ),
                ),
                (
                    "allow_review",
                    models.BooleanField(
                        default=True,
                        help_text="Allow students to review their answers after submission",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="content.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="curriculum.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
                "db_table": "quizzes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        help_text="Which attempt this is for the student (1st, 2nd, etc.)"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Started At"
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_taken",
                    models.DurationField(
                        blank=True,
                        help_text="Actual time taken to complete the quiz",
                        null=True,
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the attempt has been submitted",
                    ),
                ),
                (
                    "is_timed_out",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the attempt was auto-submitted due to time limit",
                    ),
                ),
                (
                    "total_points_possible",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total points possible at time of attempt",
                        max_digits=8,
                    ),
                ),
                (
                    "total_points_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total points earned by the student",
                        max_digits=8,
                    ),
                ),
                (
                    "score_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage score (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_graded",
                    models.BooleanField(
                        default=False, help_text="Whether all answers have been graded"
                    ),
                ),
                (
                    "auto_graded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When auto-grading was completed",
                        null=True,
                    ),
                ),
                (
                    "manually_graded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When manual grading was completed",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        editable=False,
                        help_text="IP address from which attempt was made",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        editable=False,
                        help_text="Browser/device information",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this attempt"
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Instructor who did manual grading",
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="assessment.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attempt",
                "verbose_name_plural": "Attempts",
                "db_table": "attempts",
                "ordering": ["-started_at", "-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_type", models.CharField(editable=False, max_length=10)),
                (
                    "question_object_id",
                    models.UUIDField(
                        help_text="ID of the question", verbose_name="Object ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "points_override",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override the default points for this question in this quiz",
                        null=True,
                    ),
                ),
                (
                    "question_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="assessment.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Question",
                "verbose_name_plural": "Quiz Questions",
                "db_table": "quiz_questions",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrueFalseQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("question_text", models.TextField()),
                ("points", models.PositiveIntegerField(default=1)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("essay", "Essay"),
                            ("mcq", "Multiple Choice"),
                            ("tf", "True / False"),
                        ],
                        db_index=True,
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("advanced", "Advanced"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("correct_answer", models.BooleanField()),
                ("explanation", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and discovering questions (e.g., 'python', 'beginner', 'tutorial', 'exam-prep')",
                        through="common.UUIDTaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "True / False Question",
                "verbose_name_plural": "True/False Questions",
                "db_table": "true_false_questions",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_object_id",
                    models.UUIDField(
                        help_text="ID of the question being answered",
                        verbose_name="Object ID",
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(
                        blank=True,
                        help_text="Text answer for text questions or selected choice for multiple choice",
                    ),
                ),
                (
                    "answer_boolean",
                    models.BooleanField(
                        blank=True,
                        help_text="Boolean answer for True/False questions",
                        null=True,
                    ),
                ),
                (
                    "points_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Points earned for this answer",
                        max_digits=5,
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether the answer is correct (null if not graded yet)",
                        null=True,
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Instructor feedback on the answer"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assessment.attempt",
                    ),
                ),
                (
                    "selected_choices",
                    models.ManyToManyField(
                        blank=True, related_name="answers", to="assessment.choice"
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
                "db_table": "answers",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(fields=["attempt"], name="answers_attempt_022a6b_idx"),
                    models.Index(fields=["student"], name="answers_student_99ac0b_idx"),
                ],
                "unique_together": {
                    (
                        "student",
                        "attempt",
                        "question_content_type",
                        "question_object_id",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="EssayQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("question_text", models.TextField()),
                ("points", models.PositiveIntegerField(default=1)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("essay", "Essay"),
                            ("mcq", "Multiple Choice"),
                            ("tf", "True / False"),
                        ],
                        db_index=True,
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("advanced", "Advanced"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_length",
                    models.PositiveIntegerField(
                        default=500, help_text="Maximum character length for the answer"
                    ),
                ),
                (
                    "min_length",
                    models.PositiveIntegerField(
                        default=10, help_text="Minimum character length for the answer"
                    ),
                ),
                (
                    "sample_answer",
                    models.TextField(
                        blank=True,
                        help_text="Sample or expected answer for instructor reference",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Optional explanation or additional context shown after answering.",
                    ),
                ),
                (
                    "is_auto_gradable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this question can be auto-graded using keywords",
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated keywords for auto-grading (if enabled)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and discovering questions (e.g., 'python', 'beginner', 'tutorial', 'exam-prep')",
                        through="common.UUIDTaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Essay Question",
                "verbose_name_plural": "Essay Questions",
                "db_table": "essay_questions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["question_type"], name="essay_quest_questio_698c06_idx"
                    ),
                    models.Index(
                        fields=["difficulty_level"],
                        name="essay_quest_difficu_bc3976_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="essay_quest_is_acti_1754db_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="essay_quest_created_cf32b2_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="multiplechoicequestion",
            index=models.Index(
                fields=["question_type"], name="mcq_questio_questio_1c6a64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="multiplechoicequestion",
            index=models.Index(
                fields=["difficulty_level"], name="mcq_questio_difficu_066ef5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="multiplechoicequestion",
            index=models.Index(
                fields=["is_active"], name="mcq_questio_is_acti_5dd8cf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.UniqueConstraint(
                fields=("question", "order"), name="unique_choice_order_per_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="quiz",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("subject__isnull", False), ("course__isnull", True)),
                    models.Q(("subject__isnull", True), ("course__isnull", False)),
                    _connector="OR",
                ),
                name="quiz_belongs_to_exactly_one_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["student", "quiz"], name="attempts_student_af91a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["started_at"], name="attempts_started_facd20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["is_completed"], name="attempts_is_comp_02ccd2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attempt",
            unique_together={("student", "quiz", "attempt_number")},
        ),
        migrations.AddIndex(
            model_name="quizquestion",
            index=models.Index(
                fields=["quiz", "order"], name="quiz_questi_quiz_id_76bc24_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizquestion",
            unique_together={("quiz", "question_content_type", "question_object_id")},
        ),
        migrations.AddIndex(
            model_name="truefalsequestion",
            index=models.Index(
                fields=["question_type"], name="true_false__questio_a6e2c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="truefalsequestion",
            index=models.Index(
                fields=["difficulty_level"], name="true_false__difficu_e3b990_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="truefalsequestion",
            index=models.Index(
                fields=["is_active"], name="true_false__is_acti_74c2e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="truefalsequestion",
            index=models.Index(
                fields=["created_by"], name="true_false__created_8fa6ef_idx"
            ),
        ),
    ]
