# Generated by Django 5.2.12 on 2026-03-07 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
        ("content", "0003_resource_created_by_videoresource_created_by"),
        ("curriculum", "0002_specialty_created_at_specialty_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="essayquestion",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_questions",
                to="content.course",
            ),
        ),
        migrations.AddField(
            model_name="essayquestion",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_questions",
                to="curriculum.subject",
            ),
        ),
        migrations.AddField(
            model_name="multiplechoicequestion",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_questions",
                to="content.course",
            ),
        ),
        migrations.AddField(
            model_name="multiplechoicequestion",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_questions",
                to="curriculum.subject",
            ),
        ),
        migrations.AddField(
            model_name="truefalsequestion",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_questions",
                to="content.course",
            ),
        ),
        migrations.AddField(
            model_name="truefalsequestion",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_questions",
                to="curriculum.subject",
            ),
        ),
    ]
