# Generated by Django 5.2.12 on 2026-03-11 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0002_essayquestion_course_essayquestion_subject_and_more"),
        ("content", "0005_remove_resource_resource_exactly_one_parent_and_more"),
        ("curriculum", "0010_remove_specialty_is_active_gradesubject_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="quiz",
            name="quiz_belongs_to_exactly_one_parent",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="subject",
        ),
        migrations.AddField(
            model_name="quiz",
            name="grade_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="curriculum.gradesubject",
            ),
        ),
        migrations.AddConstraint(
            model_name="quiz",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("grade_subject__isnull", False), ("course__isnull", True)
                    ),
                    models.Q(
                        ("grade_subject__isnull", True), ("course__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="quiz_belongs_to_exactly_one_parent",
            ),
        ),
    ]
