# Generated by Django 5.2.12 on 2026-03-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0003_remove_quiz_quiz_belongs_to_exactly_one_parent_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="quiz",
            name="quiz_belongs_to_exactly_one_parent",
        ),
    ]
