# Generated by Django 5.2.12 on 2026-03-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0004_remove_quiz_quiz_belongs_to_exactly_one_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_auto_gradable",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question can be auto-graded using keywords",
            ),
        ),
    ]
