# Generated by Django 5.2.12 on 2026-03-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0005_quiz_is_auto_gradable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="is_auto_gradable",
        ),
    ]
