# Generated by Django 5.2.12 on 2026-03-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0006_remove_quiz_is_auto_gradable"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_auto_gradable_snapshot",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Cached at attempt submission time.",
            ),
        ),
    ]
