# Generated by Django 5.2.12 on 2026-03-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0007_quiz_is_auto_gradable_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_free",
            field=models.BooleanField(
                default=True,
                help_text="Free resources are accessible to guest users.",
                verbose_name="Is Free",
            ),
        ),
    ]
