# Generated by Django 5.2.12 on 2026-03-05 21:49

import uuid

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("curriculum", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Full chapter title (e.g. "Les Fractions").',
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier, auto-generated from the title.",
                        max_length=220,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Display order of this chapter within the grade subject.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("first", "First Term"),
                            ("second", "Second Term"),
                            ("third", "Third Term"),
                        ],
                        help_text="The school term (trimester) this chapter is taught in.",
                        max_length=10,
                        verbose_name="Term",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional short description or learning objectives for this chapter.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive chapters are hidden from students.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "grade_subject",
                    models.ForeignKey(
                        help_text="The grade/subject combination this chapter belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="curriculum.gradesubject",
                        verbose_name="Grade Subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapter",
                "verbose_name_plural": "Chapters",
                "ordering": ["grade_subject", "order"],
                "unique_together": {("grade_subject", "order")},
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Full course title.",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier, auto-generated from the title.",
                        max_length=220,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Display order within the chapter or grade subject.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first", "First Term"),
                            ("second", "Second Term"),
                            ("third", "Third Term"),
                        ],
                        help_text="Required only for standalone courses (no chapter). Chapter-based courses inherit the term from their chapter.",
                        max_length=10,
                        null=True,
                        verbose_name="Term",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional overview or learning objectives for this course.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("advanced", "Advanced"),
                        ],
                        default="medium",
                        help_text="Overall difficulty level of this course.",
                        max_length=10,
                        verbose_name="Difficulty",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive courses are hidden from students.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        help_text="The chapter this course belongs to. Leave blank for standalone courses.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="content.chapter",
                        verbose_name="Chapter",
                    ),
                ),
                (
                    "grade_subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="The grade/subject this course belongs to directly. Only set when the course has no chapter.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="curriculum.gradesubject",
                        verbose_name="Grade Subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["chapter", "order"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the resource.",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier, auto-generated from the title.",
                        max_length=220,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("lesson", "Lesson"),
                            ("exercise", "Exercise"),
                            ("homework", "Homework"),
                            ("summary", "Summary"),
                            ("notes", "Notes"),
                            ("series", "Series"),
                            ("test", "Test"),
                            ("exam", "Exam"),
                            ("past_paper", "Past Paper"),
                            ("mock_exam", "Mock Exam"),
                            ("textbook", "Textbook"),
                            ("foreign_book", "Foreign Book"),
                            ("study_guide", "Study Guide"),
                        ],
                        help_text="Type of resource: lesson, exercise, homework, test or exam.",
                        max_length=20,
                        verbose_name="Resource Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Draft resources are only visible to their author.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("advanced", "Advanced"),
                        ],
                        default="medium",
                        help_text="Difficulty level of this specific resource.",
                        max_length=10,
                        verbose_name="Difficulty",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order within the course.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("first", "First Term"),
                            ("second", "Second Term"),
                            ("third", "Third Term"),
                        ],
                        help_text="The school term (trimester) this chapter is taught in.",
                        max_length=10,
                        verbose_name="Term",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded file (PDF, Word, video, etc.).",
                        null=True,
                        upload_to="resources/%Y/%m/",
                        verbose_name="File",
                    ),
                ),
                (
                    "solution_file",
                    models.FileField(
                        blank=True,
                        help_text="File containing the resource solution",
                        null=True,
                        upload_to="solutions/%Y/%m/",
                        verbose_name="Solution",
                    ),
                ),
                (
                    "has_solution",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether this resource has an associated solution file",
                        verbose_name="Has Solution",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Type-specific attributes. e.g. {"duration_minutes": 60, "total_marks": 20} for a test.',
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(
                        default=True,
                        help_text="Free resources are accessible to guest users.",
                        verbose_name="Is Free",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="The course this resource belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="content.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subject to which this resource belongs (mutually exclusive with course)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="curriculum.subject",
                        verbose_name="Subject",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and discovering resources (e.g., 'python', 'beginner', 'tutorial', 'exam-prep')",
                        through="common.UUIDTaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="VideoResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "youtube_url",
                    models.URLField(
                        help_text="Full YouTube URL (example: https://www.youtube.com/watch?v=abc123)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="Optional (example: 10:35)", max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="content.course",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and discovering resources (e.g., 'python', 'beginner', 'tutorial', 'exam-prep')",
                        through="common.UUIDTaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Video",
                "verbose_name_plural": "Course Videos",
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("chapter__isnull", False), ("grade_subject__isnull", True)
                    ),
                    models.Q(
                        ("chapter__isnull", True), ("grade_subject__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="course_exactly_one_parent",
                violation_error_message="A course must belong to either a chapter or a grade subject, not both.",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("chapter__isnull", False),
                    models.Q(("chapter__isnull", True), ("term__isnull", False)),
                    _connector="OR",
                ),
                name="course_standalone_requires_term",
                violation_error_message="Standalone courses (without a chapter) must have a term assigned.",
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("course__isnull", False), ("subject__isnull", True)),
                    models.Q(("course__isnull", True), ("subject__isnull", False)),
                    _connector="OR",
                ),
                name="resource_exactly_one_parent",
                violation_error_message="Resource must belong to exactly one course or subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("course__isnull", False),
                        (
                            "resource_type__in",
                            [
                                "lesson",
                                "exercise",
                                "homework",
                                "summary",
                                "notes",
                                "series",
                            ],
                        ),
                    ),
                    models.Q(
                        (
                            "resource_type__in",
                            [
                                "test",
                                "exam",
                                "past_paper",
                                "mock_exam",
                                "textbook",
                                "foreign_book",
                                "study_guide",
                            ],
                        ),
                        ("subject__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="resource_type_matches_parent",
                violation_error_message="Resource type must match parent entity requirements",
            ),
        ),
    ]
