# Generated by Django 5.2.12 on 2026-03-10 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("content", "0004_resource_file_extension_resource_file_hash_and_more"),
        ("curriculum", "0010_remove_specialty_is_active_gradesubject_is_active"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="resource",
            name="resource_exactly_one_parent",
        ),
        migrations.RemoveConstraint(
            model_name="resource",
            name="resource_type_matches_parent",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="subject",
        ),
        migrations.AddField(
            model_name="resource",
            name="grade_subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Grade subject to which this resource belongs (mutually exclusive with course)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="curriculum.gradesubject",
                verbose_name="Grade Subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("course__isnull", False), ("grade_subject__isnull", True)
                    ),
                    models.Q(
                        ("course__isnull", True), ("grade_subject__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="resource_exactly_one_parent",
                violation_error_message="Resource must belong to exactly one course or subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("course__isnull", False),
                        (
                            "resource_type__in",
                            [
                                "lesson",
                                "exercise",
                                "homework",
                                "summary",
                                "notes",
                                "series",
                            ],
                        ),
                    ),
                    models.Q(
                        ("grade_subject__isnull", False),
                        (
                            "resource_type__in",
                            [
                                "test",
                                "exam",
                                "past_paper",
                                "mock_exam",
                                "textbook",
                                "foreign_book",
                                "study_guide",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="resource_type_matches_parent",
                violation_error_message="Resource type must match parent entity requirements",
            ),
        ),
    ]
