# Generated by Django 5.2.12 on 2026-03-11 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("content", "0005_remove_resource_resource_exactly_one_parent_and_more"),
        ("curriculum", "0010_remove_specialty_is_active_gradesubject_is_active"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="download_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this resource has been downloaded",
                verbose_name="Download Count",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this resource is visible and accessible",
                verbose_name="Is Active",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this resource has been viewed",
                verbose_name="View Count",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="term",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first", "First Term"),
                    ("second", "Second Term"),
                    ("third", "Third Term"),
                ],
                help_text="The school term (trimester) this chapter is taught in.",
                max_length=10,
                verbose_name="Term",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["resource_type"], name="content_res_resourc_0bc7ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["is_active"], name="content_res_is_acti_f1815f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["course", "resource_type"],
                name="content_res_course__1d635c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["grade_subject", "resource_type"],
                name="content_res_grade_s_163c81_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["-download_count"], name="content_res_downloa_de44c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["-view_count"], name="content_res_view_co_88fb65_idx"
            ),
        ),
    ]
