# Generated by Django 5.2.12 on 2026-03-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_resource_download_count_resource_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Rich text content of the resource. Supports LaTeX (e.g. $x^2 + y^2 = z^2$) and Markdown. Used primarily for exercises, lessons, and summaries.",
                verbose_name="Content",
            ),
        ),
    ]
