# Generated by Django 5.2.12 on 2026-03-13 14:17

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0023_sci_sci_3_as"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded file (PDF, Word, video, etc.).",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="resources/%Y/%m/",
                verbose_name="File",
            ),
        ),
    ]
