# Generated by Django 5.2.12 on 2026-03-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0023_sci_sci_3_as"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="description",
            field=models.TextField(
                default="Just a description",
                help_text="Description",
                verbose_name="Description",
            ),
            preserve_default=False,
        ),
    ]
