# Generated by Django 5.2.12 on 2026-03-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0024_alter_resource_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded file (PDF, Word, video, etc.).",
                null=True,
                upload_to="resources/%Y/%m/",
                verbose_name="File",
            ),
        ),
    ]
