# Generated by Django 5.2.12 on 2026-03-05 17:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("primaire", "Primaire"),
                            ("moyen", "Moyen"),
                            ("secondaire", "Secondaire"),
                            ("university", "University"),
                        ],
                        help_text="The education level (e.g. Primaire, Moyen, Secondaire).",
                        max_length=50,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier, auto-generated from the name.",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Controls the display order of levels (e.g. 1=Primaire, 2=Moyen, 3=Secondaire).",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Level",
                "verbose_name_plural": "Levels",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Full grade name (e.g. "1ère Année Primaire").',
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text='Abbreviated grade name used in UI and slugs (e.g. "1AP").',
                        max_length=20,
                        verbose_name="Short Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier, auto-generated from the short name.",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Display order within the level (e.g. 1 for 1ère Année).",
                        verbose_name="Order",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        help_text="The education level this grade belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="curriculum.level",
                        verbose_name="Level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "ordering": ["level__order", "order"],
                "unique_together": {("level", "order")},
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Full specialty name (e.g. "Sciences Expérimentales").',
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text='Abbreviated specialty name used in UI and slugs (e.g. "SE").',
                        max_length=20,
                        verbose_name="Short Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier, auto-generated from grade and short name.",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        help_text="The Secondaire grade this specialty (filière) belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialties",
                        to="curriculum.grade",
                        verbose_name="Grade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Specialty",
                "verbose_name_plural": "Specialties",
                "unique_together": {("grade", "name")},
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Full subject name (e.g. "Mathématiques").',
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text='Abbreviated subject name used in UI (e.g. "Math").',
                        max_length=20,
                        verbose_name="Short Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier, auto-generated from level and subject name.",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text='Icon class for UI display (e.g. FontAwesome class like "fa-calculator").',
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        help_text="The education level this subject belongs to. A subject is shared across all grades of a level.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="curriculum.level",
                        verbose_name="Level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["name"],
                "unique_together": {("level", "name")},
            },
        ),
        migrations.CreateModel(
            name="GradeSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.ForeignKey(
                        help_text="The grade in which this subject is taught.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_subjects",
                        to="curriculum.grade",
                        verbose_name="Grade",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        help_text="The filière this subject is restricted to. Leave blank if the subject applies to all specialties of this grade.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grade_subjects",
                        to="curriculum.specialty",
                        verbose_name="Specialty",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject taught in this grade.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_subjects",
                        to="curriculum.subject",
                        verbose_name="Subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Subject",
                "verbose_name_plural": "Grade Subjects",
                "unique_together": {("grade", "subject", "specialty")},
            },
        ),
    ]
