# Generated by Django 5.2.12 on 2026-03-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0005_seed_subjects"),
        ("curriculum", "0006_seed_specialities"),
    ]

    operations = []
