# Generated by Django 5.2.12 on 2026-03-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0008_seed_grade_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
