# Generated by Django 5.2.12 on 2026-03-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_specialty_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='is_active',
        ),
        migrations.AddField(
            model_name='gradesubject',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
