# Generated by Django 5.2.12 on 2026-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0010_remove_specialty_is_active_gradesubject_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradesubject",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="gradesubject",
            constraint=models.UniqueConstraint(
                fields=("grade", "subject", "specialty"),
                name="unique_grade_subject_specialty",
            ),
        ),
    ]
