# Generated by Django 5.2.12 on 2026-03-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Interaction', 'verbose_name_plural': 'Interactions'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
    ]
