# Generated by Django 5.2.12 on 2026-03-20 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("feedback", "0003_alter_bookmark_student_alter_interaction_student_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bookmark",
            name="feedback_bo_student_b6493e_idx",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="False means the bookmark was removed but the row is kept for history.",
                verbose_name="Active",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["student", "active", "-created_at"],
                name="feedback_bo_student_6e11e6_idx",
            ),
        ),
    ]
