"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ
from celery.schedules import crontab

# from .logging import LOGGING

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

X_FRAME_OPTIONS = "SAMEORIGIN"

AUTH_USER_MODEL = "accounts.CustomUser"
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # thirdparty apps
    "rest_framework",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "taggit",
    "django_celery_beat",
    # internal apps
    "common",
    "apps.curriculum",
    "apps.content",
    "apps.feedback",
    "apps.progress",
    "apps.accounts",
    "apps.authentication",
    "apps.assessment",
    "apps.billing",
    "apps.tutoring",
    "apps.recommender",
]

SITE_ID = 1

DOMAIN = "http://localhost:8000"

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]


MIDDLEWARE = [
    "common.middleware.request_id.RequestIDMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # thirdparty
    "allauth.account.middleware.AccountMiddleware",
    # internal
    "apps.authentication.middleware.OnboardingMiddleware",
    "common.middleware.allauth_ratelimit.AllauthRateLimitMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Algiers"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files (user-uploaded content)
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ── Session expiry ─────────────────────────────────────────────────────────────

# Session cookie age in seconds — 4 minutes = 240 seconds
SESSION_COOKIE_AGE = 60 * 60 * 2

# Force the session to expire when the browser closes,
# regardless of SESSION_COOKIE_AGE
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Use a DB-backed session so expiry is enforced server-side too,
# not just by the cookie lifetime on the client.
# This prevents a user from manually extending their cookie.
# SESSION_ENGINE = "django.contrib.sessions.backends.db"

# If you want the session timer to reset on every request
# (i.e. "4 minutes of inactivity" rather than "4 minutes from login"):
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SECURE = False  # set True in production (HTTPS only)
SESSION_COOKIE_HTTPONLY = True  # JS cannot access the cookie
SESSION_COOKIE_SAMESITE = "Lax"


# ── Rate Limiting ──────────────────────────────────────────────────────────────
RATELIMIT_USE_CACHE = "default"
RATELIMIT_ENABLE = True

# Paths that bypass rate limiting entirely
RATELIMIT_SKIP_PATHS = [
    "/admin/",
    "/static/",
    "/media/",
]

# RATE_LIMIT_MAP = {
#     # ── Auth ──────────────────────────────────────────────────────────────────
#     "login": {
#         "key": "post:username",
#         "rate": "5/m",
#         "reason": "brute force protection",
#     },
#     "register": {"key": "ip", "rate": "3/h", "reason": "account farming"},
#     "password_reset_request": {
#         "key": "post:email",
#         "rate": "3/h",
#         "reason": "email bombing",
#     },
#     "password_reset_confirm": {
#         "key": "ip",
#         "rate": "10/h",
#         "reason": "token brute force",
#     },
#     # ── Content browsing ──────────────────────────────────────────────────────
#     "resource_detail": {
#         "key": "user_or_ip",
#         "rate": "120/m",
#         "reason": "normal browsing",
#     },
#     "course_detail": {
#         "key": "user_or_ip",
#         "rate": "120/m",
#         "reason": "normal browsing",
#     },
#     "resource_download": {
#         "key": "user_or_ip",
#         "rate": "20/m",
#         "reason": "scraping prevention",
#     },
#     # ── Search ────────────────────────────────────────────────────────────────
#     "search": {"key": "user_or_ip", "rate": "20/m", "reason": "expensive queries"},
#     # ── Student actions ───────────────────────────────────────────────────────
#     "submit_rating": {"key": "user", "rate": "10/m", "reason": "rating spam"},
#     "submit_comment": {"key": "user", "rate": "5/m", "reason": "comment spam"},
#     "mark_progress": {"key": "user", "rate": "60/m", "reason": "normal study activity"},
#     # ── API ───────────────────────────────────────────────────────────────────
#     "api_anonymous": {"key": "ip", "rate": "30/m", "reason": "abuse prevention"},
#     "api_authenticated": {"key": "user", "rate": "200/m", "reason": "normal API usage"},
# }


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "ratelimit-testing",
    }
}
# # for production
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": env("REDIS_URL"),
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         },
#     }
# }


# ── allauth core ──
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "first_name*",
    "last_name*",
    "password1*",
    "password2*",
]
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[EduGDZ] "
ACCOUNT_MAX_EMAIL_ADDRESSES = 2
ACCOUNT_SESSION_REMEMBER = True  # remember me by default
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# ACCOUNT_USERNAME_REQUIRED = False

# ── redirects ──
LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "/dashboard/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"

# ── adapter ──
ACCOUNT_ADAPTER = "apps.authentication.adapters.CustomAccountAdapter"
SOCIALACCOUNT_ADAPTER = "apps.authentication.adapters.CustomSocialAccountAdapter"

# -- forms ---
ACCOUNT_FORMS = {
    "signup": "apps.authentication.forms.CustomSignupForm",
    "login": "apps.authentication.forms.CustomLoginForm",
    "reset_password": "apps.authentication.forms.CustomResetPasswordForm",
    "change_password": "apps.authentication.forms.CustomChangePasswordForm",
}

# SOCIALACCOUNT_FORMS = {
#     "signup": "apps.authentication.forms.CustomSocialSignupForm",
# }

# ── social ──
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID", default=""),
            "secret": env("GOOGLE_CLIENT_SECRET", default=""),
            # 'key':           '',
        },
        "SCOPE": ["profile", "email"],
        # 'AUTH_PARAMS': {'access_type': 'online'},
        "FETCH_USERINFO": True,
        "AUTH_PARAMS": {"access_type": "online", "prompt": "select_account"},
        "OAUTH_PKCE_ENABLED": True,
    }
}

ACCOUNT_RATE_LIMITS = {
    # ── Login ──────────────────────────────────────────────────────────────────
    # 5 failed login attempts per 5 minutes per IP
    "login_failed": "5/5m",
    # ── Signup ─────────────────────────────────────────────────────────────────
    # 5 signups per hour per IP — prevents account farming
    "signup": "5/h",
    # ── Password reset ─────────────────────────────────────────────────────────
    # 3 reset emails per hour per IP
    "reset_password": "3/h",
    # 10 reset confirmation attempts per hour — prevents token brute force
    "reset_password_from_key": "10/h",
    # ── Email confirmation ──────────────────────────────────────────────────────
    # 3 confirmation email resends per hour
    "confirm_email": "3/h",
    # ── 2FA (if you use it) ────────────────────────────────────────────────────
    "login_by_code": "5/m",  # OTP submission
    "request_login_by_code": "5/m",  # OTP request
    # ── Email management ────────────────────────────────────────────────────────
    "add_email": "5/h",  # adding a new email address
    "change_password": "5/h",  # password change form
}

# ── email backend (dev) ──
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# ── Email (real SMTP) ──
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False  # must be False when TLS is Tr


CONTACT_EMAIL = "xolonalibto66038@gmail.com"


# Stripe settings

STRIPE_TEST_SECRET_KEY = env("STRIPE_SECRET_KEY", default="")
STRIPE_PUBLISHABLE_KEY = env("STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_ENDPOINT_SECRET = env("STRIPE_ENDPOINT_SECRET", default="")
# STRIPE_PRICE_ID = env('STRIPE_PRICE_ID',     default='')
PLATFORM_FEE_PERCENT = env("PLATFORM_FEE_PERCENT", default="20")
STRIPE_CURRENCY = env("STRIPE_CURRENCY", default="usd")

# Zoom settings

ZOOM_ACCOUNT_ID = env("ZOOM_ACCOUNT_ID", default="")
ZOOM_CLIENT_ID = env("ZOOM_CLIENT_ID", default="")
ZOOM_CLIENT_SECRET = env("ZOOM_CLIENT_SECRET", default="")
ZOOM_BASE_URL = env("ZOOM_BASE_URL", default="")
ZOMM_SECRET_TOKEN = env("ZOMM_SECRET_TOKEN", default="")
ZOOM_WEBHOOK_SECRET = env("ZOOM_WEBHOOK_SECRET", default="")
ZOOM_HOST_EMAIL = env("ZOOM_HOST_EMAIL", default="")

# Google meet settings

GOOGLE_SERVICE_ACCOUNT_FILE = env("GOOGLE_SERVICE_ACCOUNT_FILE")
GOOGLE_CALENDAR_HOST_EMAIL = env("GOOGLE_CALENDAR_HOST_EMAIL")


# Broker (Redis)
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_BROKER_URL = env("REDIS_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

# Serialization
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# Timezone (important — matches Django's timezone)
CELERY_TIMEZONE = TIME_ZONE

# Prevent tasks from piling up if the worker was down for a while
CELERY_BEAT_MAX_LOOP_INTERVAL = 300  # seconds
