# Generated by Django 5.2.12 on 2026-03-09 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('teacher_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_authorized', 'Payment Authorized'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('payment_failed', 'Payment Failed'), ('canceled', 'Canceled')], max_length=32)),
                ('stripe_checkout_session_id', models.CharField(max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(max_length=255, null=True, unique=True)),
                ('stripe_transfer_id', models.CharField(max_length=255, null=True)),
                ('payment_authorized_at', models.DateTimeField(null=True)),
                ('scheduled_at', models.DateTimeField(null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('zoom_meeting_id', models.CharField(max_length=255, null=True)),
                ('zoom_join_url', models.URLField(null=True)),
                ('zoom_start_url', models.URLField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('teacher_paid', models.BooleanField(default=False)),
                ('teacher_paid_at', models.DateTimeField(null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
