# Generated by Django 5.2.12 on 2026-03-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringsession",
            name="meeting_event_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tutoringsession",
            name="meeting_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tutoringsession",
            name="meeting_join_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="tutoringsession",
            name="meeting_start_url",
            field=models.URLField(null=True),
        ),
    ]
