# Generated by Django 5.2.12 on 2026-03-18 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0002_tutoringsession_meeting_event_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringsession",
            name="canceled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="canceled_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
