# Generated by Django 5.2.12 on 2026-03-24 14:24

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0003_tutoringsession_canceled_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposed_start", models.DateTimeField()),
                ("proposed_end", models.DateTimeField()),
                ("confirmed_start", models.DateTimeField(blank=True, null=True)),
                ("confirmed_end", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("price_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_currency", models.CharField(default="DZD", max_length=3)),
                (
                    "state",
                    django_fsm.FSMField(
                        default="pending_teacher", max_length=50, protected=True
                    ),
                ),
                ("google_event_id", models.CharField(blank=True, max_length=255)),
                ("google_meet_link", models.URLField(blank=True)),
                ("google_calendar_link", models.URLField(blank=True)),
                ("max_participants", models.PositiveIntegerField(default=1)),
                ("join_code", models.CharField(blank=True, max_length=16)),
                ("teacher_notes", models.TextField(blank=True)),
                ("student_notes", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutoring_sessions_as_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutoring_sessions_as_teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
