# Generated by Django 5.2.12 on 2026-03-28 13:52

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0004_googlesession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlesession",
            name="max_participants",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name="ZoomSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("proposed_start", models.DateTimeField()),
                ("proposed_end", models.DateTimeField()),
                ("confirmed_start", models.DateTimeField(blank=True, null=True)),
                ("confirmed_end", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("platform_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "teacher_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("price_currency", models.CharField(default="DZD", max_length=3)),
                (
                    "state",
                    django_fsm.FSMField(
                        default="pending_teacher", max_length=50, protected=True
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "stripe_transfer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payment_authorized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "zoom_meeting_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("zoom_join_url", models.URLField(blank=True, null=True)),
                ("zoom_start_url", models.URLField(blank=True, null=True)),
                (
                    "zoom_password",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("teacher_paid", models.BooleanField(default=False)),
                ("teacher_paid_at", models.DateTimeField(blank=True, null=True)),
                ("teacher_notes", models.TextField(blank=True)),
                ("student_notes", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "canceled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canceled_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teacher_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="TutoringSession",
        ),
    ]
