# Generated by Django 5.2.12 on 2026-03-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0005_alter_googlesession_max_participants_zoomsession_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zoomsession",
            name="platform_fee",
        ),
    ]
