# Generated by Django 5.2.12 on 2026-03-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0006_remove_zoomsession_platform_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zoomsession",
            name="teacher_amount",
        ),
    ]
