# apps/accounts/choices.py

from django.db.models import TextChoices
from django.utils.translation import gettext_lazy as _


class UserRole(TextChoices):
    STUDENT = "student", _("Student")
    TEACHER = "teacher", _("Teacher")


class Gender(TextChoices):
    MALE = "male", _("Male")
    FEMALE = "female", _("Female")


class Wilaya(TextChoices):
    ADRAR = "01", _("Adrar")
    CHLEF = "02", _("Chlef")
    LAGHOUAT = "03", _("Laghouat")
    OUM_EL_BOUAGHI = "04", _("Oum El Bouaghi")
    BATNA = "05", _("Batna")
    BEJAIA = "06", _("Béjaïa")
    BISKRA = "07", _("Biskra")
    BECHAR = "08", _("Béchar")
    BLIDA = "09", _("Blida")
    BOUIRA = "10", _("Bouira")
    TAMANRASSET = "11", _("Tamanrasset")
    TEBESSA = "12", _("Tébessa")
    TLEMCEN = "13", _("Tlemcen")
    TIARET = "14", _("Tiaret")
    TIZI_OUZOU = "15", _("Tizi Ouzou")
    ALGIERS = "16", _("Alger")
    DJELFA = "17", _("Djelfa")
    JIJEL = "18", _("Jijel")
    SETIF = "19", _("Sétif")
    SAIDA = "20", _("Saïda")
    SKIKDA = "21", _("Skikda")
    SIDI_BEL_ABBES = "22", _("Sidi Bel Abbès")
    ANNABA = "23", _("Annaba")
    GUELMA = "24", _("Guelma")
    CONSTANTINE = "25", _("Constantine")
    MEDEA = "26", _("Médéa")
    MOSTAGANEM = "27", _("Mostaganem")
    MSILA = "28", _("M'Sila")
    MASCARA = "29", _("Mascara")
    OUARGLA = "30", _("Ouargla")
    ORAN = "31", _("Oran")
    EL_BAYADH = "32", _("El Bayadh")
    ILLIZI = "33", _("Illizi")
    BORDJ_BOU_ARRERIDJ = "34", _("Bordj Bou Arréridj")
    BOUMERDES = "35", _("Boumerdès")
    EL_TARF = "36", _("El Tarf")
    TINDOUF = "37", _("Tindouf")
    TISSEMSILT = "38", _("Tissemsilt")
    EL_OUED = "39", _("El Oued")
    KHENCHELA = "40", _("Khenchela")
    SOUK_AHRAS = "41", _("Souk Ahras")
    TIPAZA = "42", _("Tipaza")
    MILA = "43", _("Mila")
    AIN_DEFLA = "44", _("Aïn Defla")
    NAAMA = "45", _("Naâma")
    AIN_TEMOUCHENT = "46", _("Aïn Témouchent")
    GHARDAIA = "47", _("Ghardaïa")
    RELIZANE = "48", _("Relizane")
    TIMIMOUN = "49", _("Timimoun")
    BORDJ_BADJI_MOKHTAR = "50", _("Bordj Badji Mokhtar")
    OULED_DJELLAL = "51", _("Ouled Djellal")
    BENI_ABBES = "52", _("Béni Abbès")
    IN_SALAH = "53", _("In Salah")
    IN_GUEZZAM = "54", _("In Guezzam")
    TOUGGOURT = "55", _("Touggourt")
    DJANET = "56", _("Djanet")
    EL_MEGHAIER = "57", _("El M'Ghair")
    EL_MENIAA = "58", _("El Ménéa")
