# Generated by Django 5.2.12 on 2026-03-14 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemFeatureVector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "object_id",
                    models.UUIDField(db_index=True, verbose_name="Object ID"),
                ),
                (
                    "level_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Cached level PK (Primaire / Moyen / Secondaire / Université).",
                        null=True,
                        verbose_name="Level ID",
                    ),
                ),
                (
                    "grade_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Cached grade PK (e.g. 3AM, 1AS).",
                        null=True,
                        verbose_name="Grade ID",
                    ),
                ),
                (
                    "subject_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Cached subject PK (e.g. Mathématiques, Physique).",
                        null=True,
                        verbose_name="Subject ID",
                    ),
                ),
                (
                    "specialty_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Cached specialty (filière) PK. NULL means the item applies to all specialties of this grade.",
                        null=True,
                        verbose_name="Specialty ID",
                    ),
                ),
                (
                    "course_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Cached course PK. NULL for subject-level items (test/exam).",
                        null=True,
                        verbose_name="Course ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("lesson", "Lesson"),
                            ("exercise", "Exercise"),
                            ("homework", "Homework"),
                            ("test", "Test"),
                            ("exam", "Exam"),
                        ],
                        help_text="Discriminator used by the engine to boost same-type matches.",
                        max_length=20,
                        verbose_name="Item Type",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("advanced", "Advanced"),
                        ],
                        help_text="Cached difficulty level. NULL when not applicable.",
                        max_length=10,
                        null=True,
                        verbose_name="Difficulty",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first", "First Term"),
                            ("second", "Second Term"),
                            ("third", "Third Term"),
                        ],
                        help_text="Cached school term. NULL when not applicable.",
                        max_length=10,
                        null=True,
                        verbose_name="Term",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last sync by the recommendation pipeline. Distinct from updated_at (inherited from TimeStampModel) which tracks Django model saves.",
                        verbose_name="Last Synced At",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Feature Vector",
                "verbose_name_plural": "Item Feature Vectors",
                "indexes": [
                    models.Index(
                        fields=["level_id", "grade_id", "subject_id"],
                        name="ifv_level_grade_subject_idx",
                    ),
                    models.Index(fields=["specialty_id"], name="ifv_specialty_idx"),
                    models.Index(fields=["item_type"], name="ifv_item_type_idx"),
                    models.Index(fields=["term"], name="ifv_term_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id"),
                        name="unique_item_feature_vector",
                    )
                ],
            },
        ),
    ]
